version: '3.8'

services:
  fullstack:
    context: .
    dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8080:8080
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 10s

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=userdb'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d userdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
